# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ "main" ]
    # Pattern matched against refs/tags
    tags:        
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull code from tag
        run: echo pull code from tag
      - name: build project from tag
        run: echo yarn nx build
      - name: build Docker with tag
        run: echo yarn buildimage
      - name: upload dockerImage to artifact
        run: echo upload artifact

      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.npm_token}}

 
